name: bazarr-tak
title: bazarr-tak
summary: UnOfficial release of Bazarr
description: |
  **Bazarr is a companion application to Sonarr and Radarr that manages 
  and downloads subtitles based on your requirements.**\
  You define your preferences by TV show or movie and Bazarr takes care 
  of everything for you.
  
  Be aware that Bazarr doesn't scan disk to detect series and movies: 
  It only takes care of the series and movies that are indexed in Sonarr and Radarr.

  * The web interface is accessible by default at http://localhost:6767
  * See https://bazarr.media for more details.


  **Bazarr Release**
  * 'ffmpeg-tak' and 'mesa-2604' snaps are required as dependencies.
  * Build with sqlite (database), ffmpeg + mediainfo (metadata), unar (decompress)
  * Service is restarted on any condition.

  **Post install commands required to access media folders and see resources :**

  sudo snap connect bazarr-tak:removable-media

  sudo snap connect bazarr-tak:mount-observe
  
  **!!! Files can only be written in a directory owned by 'root' !!!**\
  **!!! Home base directory content is not readable !!!**
  
  This is due to current behavior and restrictions of snaps by Canonical.\
  Check documentation if you want to setup data in /home directory: https://github.com/TehAppKiller/Snapcraft-common-doc/blob/main/README.md#FAQ
website: https://bazarr.media
source-code: https://github.com/TehAppKiller/bazarr-tak
issues: https://github.com/TehAppKiller/bazarr-tak/issues
contact: ['mailto:tehappkiller@proton.me', 'https://mastodon.social/@TehAppKiller']
donation: https://whydonate.com/en/fundraising/help-teh-devz
license: MIT
icon: icon.png
grade: stable
confinement: strict
base: core26
adopt-info: bazarr
platforms:
  amd64:
  arm64:
  #armhf: # Dropped ; possible but complicated due to python modules not available as binaries
  
plugs:
  ffmpeg:
    interface: content
    target: $SNAP/ffmpeg
    default-provider: ffmpeg-tak # snap used
    content: ffmpeg # slot name called
    
# Add deadsnakes ppa to have access to custom Python version
package-repositories:
  - type: apt
    ppa: deadsnakes/ppa

apps:
  bazarr:
    extensions: [gpu]
    command-chain: [snap/command-chain/gpu-2604-wrapper]
    command: bin/run-bazarr.sh
    daemon: simple
    restart-condition: always
    plugs:
      - mount-observe
      - network
      - network-bind
      - removable-media
      - home # useless for now ; if snaps are allowed to read /home folder one day...
    environment:
      LD_LIBRARY_PATH: $SNAP/ffmpeg/usr/lib/:$SNAP/ffmpeg/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/ffmpeg/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio/:$SNAP/ffmpeg/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/sdl2-classic/:$LD_LIBRARY_PATH
      PATH: $SNAP/ffmpeg/usr/bin/:$PATH
      PYTHONPATH: $SNAP/lib/python3.13/site-packages:$PYTHONPATH # Temp fix as python-plugin does not work ; as using python runtime with venv modules ; does NOT prevent python-plugin mess with the python env of snapcraft build

parts:
  python-runtime: # use python 13 ; 14 not supported by all modules yet
    plugin: nil
    stage-packages:
      - python3.13-venv # (python3 package does not include venv)
      
  bazarr:
    after:
      - python-runtime
    plugin: python
    python-requirements:
      - requirements.txt
    build-environment:
      - PARTS_PYTHON_INTERPRETER: python3.13
    source: .
    override-pull: |
      # Pull
      rm -rf $CRAFT_PART_SRC/{,.[!.],..?}*
      download_url=$(curl -sL https://api.github.com/repos/morpheus65535/bazarr/releases/latest | sed -nre "s/^.*\"browser_download_url\": \"([^\"]*)\".*/\1/p")
      wget "${download_url}" -O srcfile
      unzip srcfile
      
      craftctl default
    override-build: |
      # Get Last Source Tag version and Check Snap (with same Source) version
      src_version=$(curl -sL https://api.github.com/repos/morpheus65535/bazarr/releases/latest | sed -nre "s/^.*\/download\/v([^\/]*)\/.*/\1/p")
      echo "Source last tag: ${src_version}"
      snap_last_version=$(curl -sL -H "Snap-Device-Series: 16" "https://api.snapcraft.io/v2/snaps/info/bazarr-tak?architecture=${CRAFT_ARCH_BUILD_FOR}&fields=version" | sed -nre "s/^.*\"stable\"\,\"track\"\:\"latest\"\}\,\"version\"\:\"([^\"]*)\".*/\1/p");
      echo "Snap last version: ${snap_last_version}"
      snap_build_with_same_version=$(echo $snap_last_version | sed -nre "s/^($src_version.*).*/\1/p");
      # Same version ?
      if [ -z "$snap_build_with_same_version" ]
      then
        new_snap_version="${src_version}";
      else
        # Get snap build version
        snap_build=$(echo $snap_build_with_same_version | sed -nre 's/^.*-v([0-9]*).*/\1/p');
        # Already a build version ?
        if [ -z "$snap_build" ]
        then
          # init @v2
          new_snap_build="2";
        else
          # increment @v+1
          new_snap_build=$(($snap_build+1));
        fi

        new_snap_version="${src_version}-v${new_snap_build}";
      fi

       craftctl set version=$new_snap_version

      # Build
      INST_DIR="$CRAFT_PART_INSTALL/Bazarr"
      mkdir -p "$INST_DIR"
      cp -a ./* $INST_DIR
      
      craftctl default
    build-packages:
      - curl
      - wget
      - unzip

  local:
    plugin: dump
    source: snap/local
    override-prime: |
      craftctl default
      chmod +rx $CRAFT_PRIME/bin/run-bazarr.sh

  deps:
    plugin: nil
    source: .
    stage-packages:
      - sqlite3 # required by Bazarr (database)
      - unar # required by Bazarr (decompress files)
      #- ffmpeg # WAS required by Bazarr (codecs info...) -> (externalized)
      - mediainfo # optional alternative to ffprobe for Bazarr codecs info (Bazar menu option)
      - libxml2-16 # required by python-lxml
      - libxslt1.1 # required by python-lxml
      #- libatlas3-base # =(blas+lapack) WAS required by numpy (included in binaries) and ffmpeg -> (externalized)
      #- libglu1-mesa # WAS required by ffmpeg caca ; caca removed from core26 ubuntu ffmpeg packages + externalized
      #- libglut3.12 # WAS required by ffmpeg caca ; caca removed from core26 ubuntu ffmpeg packages + externalized
      
